name: namaz_clock_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0' # SDK range specify kiya gaya

dependencies:
  flutter:
    sdk: flutter
  
  # --- Firebase Core & Services ---
  firebase_core: ^3.15.0       # Firebase services ko initialize karne ke liye
  firebase_auth: ^5.6.1        # User authentication ke liye
  cloud_firestore: ^5.6.10     # Firestore database ke liye
  firebase_messaging: ^15.2.8  # Push notifications (FCM) ke liye
  # firebase_storage: ^12.4.8    # Image aur files upload karne ke liye (agar istemal karna ho)

  # --- Local Notifications & Prayer Timings ---
  flutter_local_notifications: ^19.3.0 # Client-side notifications aur alarms ke liye
  flutter_timezone: ^4.1.1       # Device ka timezone detect karne ke liye
  timezone: ^0.10.1              # Timezone calculations ke liye
  adhan: ^2.0.0+1                # Namaz ke waqt (prayer times) calculate karne ke liye
  hijri: ^3.0.0                  # Hijri (Islamic) calendar ke liye
  workmanager: ^0.9.0+2

  # --- Location, Qibla & Map ---
  geolocator: ^14.0.1            # User ki location get karne ke liye
  flutter_compass: ^0.8.0        # Qibla direction ke liye compass access
  geodesy: ^0.10.2              # Geographic calculations ke liye

  # --- UI & Utility Packages ---
  provider: ^6.1.5               # State management ke liye
  intl: ^0.20.2                  # Dates aur numbers ko format karne ke liye
  font_awesome_flutter: ^10.6.0  # Awesome icons ke liye
  cupertino_icons: ^1.0.8        # iOS-style icons ke liye
  flutter_svg: ^2.0.7            # SVG images ke liye
  image_picker: ^1.0.4           # Gallery aur camera se image pick karne ke liye
  url_launcher: ^6.3.0           # URLs ko launch karne ke liye
  permission_handler: ^12.0.1    # App permissions (location, notifications) manage karne ke liye
  uuid: ^4.2.2                   # Unique IDs generate karne ke liye
  cloudinary_public: 0.20.0      # Cloudinary service ke liye (agar istemal karna ho)
  
  # --- Localization & Translation ---
  flutter_localizations:
    sdk: flutter
  google_translator: ^1.0.0      # Text translation ke liye
  google_maps_flutter: ^2.12.3
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  geocoding: ^2.0.5
  youtube_player_iframe: ^5.1.2
  shared_preferences: ^2.5.3
  android_intent_plus: ^5.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/svg/
dependency_overrides:
  flutter_inappwebview: ^6.1.5    