// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIx5MEEPT-9cbRCedAItREea5EDCkejbI',
    appId: '1:844104997239:web:b52eec73a27cf49a22a972',
    messagingSenderId: '844104997239',
    projectId: 'namaz-colck-app',
    authDomain: 'namaz-colck-app.firebaseapp.com',
    storageBucket: 'namaz-colck-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEQrSz2K8eyTHseaMeCGxiOfeTiVbDdMo',
    appId: '1:844104997239:android:b9d61f746ba2c28022a972',
    messagingSenderId: '844104997239',
    projectId: 'namaz-colck-app',
    storageBucket: 'namaz-colck-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRs_RCHS1MapGkOY6c1KKbFb68iRUjYdc',
    appId: '1:844104997239:ios:1a96c42ced1963f922a972',
    messagingSenderId: '844104997239',
    projectId: 'namaz-colck-app',
    storageBucket: 'namaz-colck-app.firebasestorage.app',
    iosBundleId: 'com.example.namazClockApp',
  );
}
